### ISSUE TITLE
Layout support

### ISSUE THREAD

**Issue by MrLuje** [giraffe-fsharp/Giraffe.Razor#1]
I started to play with a basic sample which contains a view structure like :
/Views/Shared/_Layout.cshtml
/Views/_ViewStart.cshtml
/Views/Test.cshtml

_ViewStart.cshtml contains :
`@{
    Layout = "_Layout";
}`

Then bootstrapped with
`let viewsFolderPath = Path.Combine(env.ContentRootPath, "views")
services.AddRazorEngine(viewsFolderPath) |> ignore`
and
`razorHtmlView "Test" model`

It fails with the following stack :

> Object reference not set to an instance of an object.
>    at Microsoft.AspNetCore.Mvc.Internal.NormalizedRouteValue.GetNormalizedRouteValue(ActionContext context, String key)
>    at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pageName, Boolean isMainPage)
>    at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindPage(ActionContext context, String pageName)
>    at Microsoft.AspNetCore.Mvc.Razor.RazorView.GetLayoutPage(ViewContext context, String executingFilePath, String layoutPath)
>    at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderLayoutAsync>d__18.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderAsync>d__14.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Giraffe.Razor.RazorEngine.body@1[T](HttpContext httpContext, ActionContext actionContext, IView view, ViewDataDictionary`1 viewDataDict, TempDataDictionary tempDataDict, HtmlHelperOptions htmlHelperOptions, StringWriter _arg1)
>    at Giraffe.Razor.RazorEngine.renderView@39-2.Invoke(Unit unitVar0)
>    at Giraffe.TaskBuilder.tryFinally[a](FSharpFunc`2 step, FSharpFunc`2 fin)
>    at Giraffe.TaskBuilder.run[a](FSharpFunc`2 firstStep)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Giraffe.Razor.HttpHandlers.razorView@20.Invoke(Unit unitVar)
>    at Giraffe.TaskBuilder.run[a](FSharpFunc`2 firstStep)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Giraffe.HttpHandlers.chooseHttpFunc@94.Invoke(Unit unitVar)
>    at Giraffe.TaskBuilder.run[a](FSharpFunc`2 firstStep)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Giraffe.HttpHandlers.handlerWithRootedPath@60.Invoke(Unit unitVar)
>    at Giraffe.TaskBuilder.run[a](FSharpFunc`2 firstStep)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Giraffe.HttpHandlers.chooseHttpFunc@94.Invoke(Unit unitVar)
>    at Giraffe.TaskBuilder.run[a](FSharpFunc`2 firstStep)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Giraffe.HttpHandlers.chooseHttpFunc@94.Invoke(Unit unitVar)
>    at Giraffe.TaskBuilder.run[a](FSharpFunc`2 firstStep)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Giraffe.Middleware.Invoke@39.Invoke(Unit unitVar)
>    at Giraffe.TaskBuilder.run[a](FSharpFunc`2 firstStep)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Giraffe.Middleware.Invoke@64-7.Invoke(Unit unitVar)
>    at Giraffe.TaskBuilder.tryWith[a](FSharpFunc`2 step, FSharpFunc`2 catch)

Without the layout defined, it works flawlessly
Any help on this one ?

Thanks

**Comment by JonCanning** [comment]
I have ViewStart and Layout in the same dir and it works, so I'd suggest

`@{ Layout = "Shared/_Layout"; }`

**Comment by MrLuje** [comment]
Same issue, unfortunatly

In fact, I also have the issue from the [sample project ](https://github.com/giraffe-fsharp/Giraffe.Razor/tree/master/samples/GiraffeRazorSample)
Trying to hit the /person route gives the same stack as mine

**Comment by dustinmoris** [comment]
Should be fixed with the latest release now: https://github.com/giraffe-fsharp/Giraffe.Razor/releases/tag/v1.2.0
