### ISSUE TITLE
Tried to get the GiraffeSample to work but fail - Record label 'Text' is not defined.

### ISSUE THREAD

**Issue by SoulFireMage** [giraffe-fsharp/Giraffe.Razor#2]
I've had a good go at making this run today, trying things out. Apart from a number of packages that took me some time to work out how to include, I'm still left with this issue that I can't fix, even by looking at the source. I'm out of practice F# wise I know but this seems a very weird problem to have. 

I did try a few variations of opening various libraries but no go.

It isn't critical as I was just experimenting but it's brickwalled me for today's playing around. Maybe someone can shed some light?

![image](https://user-images.githubusercontent.com/2396080/35683069-b3792076-075a-11e8-90f4-bd67c4c43dee.png)

**Comment by dustinmoris** [comment]
Hi, sorry for the late reply, but did you get around to fix this? All the sample projects in all the Giraffe repos are being build and tested as part of each build, so if you take the code from there or if you [create a new Giraffe app through the dotnet new command](https://github.com/giraffe-fsharp/giraffe-template) then these things should work out of the box.

Please let me know if you still have problems!
