### ISSUE TITLE
Add support for organizing views into folders

### ISSUE THREAD

**Issue by odytrice** [giraffe-fsharp/Giraffe.Razor#3]
Currently, Templates must be in root Views directory which is fine for small applications but quickly becomes gnarly for large or Razor heavy applications.

One should be able to enter something like `razorHtmlView "home/index"` would get the file `/Views/Home/Index.cshtml`

**Comment by dustinmoris** [comment]
Your fix has been released: https://github.com/giraffe-fsharp/Giraffe.Razor/releases/tag/v1.2.0
