### ISSUE TITLE
Expose ModelStateDictionary

### ISSUE THREAD

**Issue by sasmithjr** [giraffe-fsharp/Giraffe.Razor#8]
I was wondering what your thoughts were on adding a parameter to `RazorEngine.renderView` to pass in a `ModelStateDictionary option`. I understand that you don't want to expose a lot of attribute-based validation in Giraffe (per [this](https://github.com/giraffe-fsharp/Giraffe/issues/121#issuecomment-364922132) discussion), so that's why I'm suggesting only adding the parameter to `renderView` and not to the handlers (also, it's less likely to break most existing users of the library if the change isn't to the http handlers).

I'm not a Razor expert, to be clear; I was converting an existing C# example ([this](https://github.com/openiddict/openiddict-samples/tree/0008db58412a39b140dd18be9189d8ed3173302c/samples/ImplicitFlow/AuthorizationServer)) to F# w/ Giraffe.Razor to learn and ran in to this issue. I bumped in to this is because I was trying to use `Microsoft.AspNetCore.Mvc.TagHelpers`, specifically `asp-validation-summary`, to reuse the same view while providing form validation feedback to the user in the [Login view](https://github.com/openiddict/openiddict-samples/blob/0008db58412a39b140dd18be9189d8ed3173302c/samples/ImplicitFlow/AuthorizationServer/Views/Account/Login.cshtml).

I can create a PR if you're okay with adding this parameter to `RazorEngine.renderView`, but it would be a breaking change.

Edit: Currently, an empty `ModelStateDictionary` is created [here](https://github.com/giraffe-fsharp/Giraffe.Razor/blob/3de1c096b8a18275bbdde0204a401002a9fb727c/src/Giraffe.Razor/RazorEngine.fs#L69).

**Comment by dustinmoris** [comment]
I think wanting to pass in a `ModelStateDictionary` is probably a reasonable change, because it is an integral part of the Razor experience, so I'm happy with this change.

Feel free to provide a PR and we can take it from there!

**Comment by Lanayx** [comment]
Hi! Just updated the package and found this breaking change... Just wanted to suggest [that idea](https://github.com/giraffe-fsharp/Giraffe.Razor/pull/7/files#r215079391) one more time, instead of adding more and more parameters to the handler to group them into VieModel type, since with each new parameter changes will be breaking again and again...
